<script type="text/javascript">
    $(document).ready(function(){
        $('#accordion').accordion({
            active: false,
            collapsible: true,
            autoHeight: false
        });
        $('.tabs').tabs();
        $(".tooltip").tooltip({track: true});
    });
</script>
<div id="accordion">
<? if (!$this->outputCache->start('accordion')): ?>

    <? $i=0; foreach ($this->zfService->getRecentActivity($this->repo) as $component => $details): $i++;?>
        <h3>
            <a href="#"><?=$component;?>
                <span class="floatRight"><?=$details['latest']->format(false ?: 'M d, Y H:i O');?></span>
            </a> 
        </h3>
        <div>
            <div class="tabs">
                <ul>
                    <li><a href="#latest-commits-<?=$i;?>">Latest Commits (<?=count($details['commits']);?>)</a></li>
                    <li><a href="#active-branches-<?=$i;?>">Active Branches (<?=count($details['all-branches']);?>)</a></li>
                </ul>
                <div id="latest-commits-<?=$i;?>" class="latest-commits">
                    <ul>
                        <? $j=0; foreach($details['commits'] as $hash => $commit): $j++;?>
                            <li title="<?=htmlentities(nl2br($commit->getMessage()));?>" class="commit tooltip nostyle <? if(($j)%2): ?>even<? else: ?>odd<? endif; ?>">
                                <span class="date floatRight"><?= $commit->getAuthorTime()->format(false ?: 'M d, Y H:i O');?></span>
                                <img src="https://secure.gravatar.com/avatar/<?= $commit->getAuthorGravatar(); ?>?s=40&d=http://framework.zend.com/wiki/s/en/2148/48/_/images/icons/profilepics/anonymous.png" class="floatLeft" />
                                &nbsp;<strong>Author:</strong> <?= $commit->getAuthorName(); ?> &lt;<?=$commit->getAuthorEmail();?>&gt;
                                <? if ($commit->getAuthorEmail() != $commit->getCommitterEmail()): ?>
                                    (Committed by <?= $commit->getCommitterName(); ?>)
                                <? endif; ?>
                                <br/> 
                                &nbsp;<strong>Commit:</strong> <a href="https://github.com/<?= $this->gh->emailToUsername($commit->getAuthorEmail(), $this->repo); ?>/zf2/commit/<?= $hash; ?>" target="_blank"><?= substr($hash, 0, 7); ?></a> 
                                <span style="padding: 5px 5px 0px 5px; display: block; clear: both;"><?= htmlentities($commit->getSubject()); ?></span></li>
                        <? endforeach; ?>                                 
                    </ul>
                </div>
                <div id="active-branches-<?=$i;?>" class="active-branches">
                    <? foreach ($details['remotes'] as $remote => $branches): ?>
                        <div class="contrib-branches">
                            <ul>
                                <? foreach ($branches as $branch => $hashes): ?>
                                <li><?=$remote;?>/<?=$branch?>
                                    <ul>
                                        <? $j=0; foreach ($hashes as $hash): $j++; ?>
                                            <? $commit = $details['commits'][$hash]; ?>
                                            <li title="<?=htmlentities(nl2br($commit->getMessage()));?>" class="commit tooltip nostyle <? if(($j)%2): ?>even<? else: ?>odd<? endif; ?>">
                                                <span class="date floatRight"><?= $commit->getAuthorTime()->format(false ?: 'M d, Y H:i O');?></span>
                                                <img src="https://secure.gravatar.com/avatar/<?= $commit->getAuthorGravatar(); ?>?s=40&d=http://framework.zend.com/wiki/s/en/2148/48/_/images/icons/profilepics/anonymous.png" class="floatLeft" />
                                                &nbsp;<strong>Author:</strong> <?= $commit->getAuthorName(); ?> &lt;<?=$commit->getAuthorEmail();?>&gt;
                                                <? if ($commit->getAuthorEmail() != $commit->getCommitterEmail()): ?>
                                                    (Committed by <?= $commit->getCommitterName(); ?>)
                                                <? endif; ?>
                                                <br/> 
                                                &nbsp;<strong>Commit:</strong> <a href="https://github.com/<?= $this->gh->emailToUsername($commit->getAuthorEmail(), $this->repo); ?>/zf2/commit/<?= $hash; ?>" target="_blank"><?= substr($hash, 0, 7); ?></a> 
                                                <span style="padding: 5px 5px 0px 5px; display: block; clear: both;"><?= htmlentities($commit->getSubject()); ?></span></li>

                                        <? endforeach; ?>
                                    </ul>
                                </li>
                                <? endforeach; ?>
                            </ul>
                        </div>
                    <? endforeach; ?>
                </div>
            </div>
        </div>
    <? endforeach; ?>
    <? $this->outputCache->end(); ?>
<? endif; ?>
</div>
