<script type="text/javascript">
    $(document).ready(function(){
        $('#accordion').accordion({
            active: false,
            collapsible: true,
            autoHeight: false
        });
        $('.tabs').tabs();
        $(".tooltip").tooltip({track: true});
    });
</script>
<div id="accordion">
    <? foreach ($this->zfComponents as $component => $details): ?>
        <h3>
            <a href="#"><?=$component;?>
                <span class="floatRight"><?=$details['latest']->format(false ?: 'M d, Y H:i O');?></span>
            </a> 
        </h3>
        <div>
            <? foreach ($details['remotes'] as $remote => $branches): ?>
                <div class="contrib-branches">
                <h3>&nbsp; <a href="https://github.com/<?= $remote; ?>" target="_blank"><img src="https://secure.gravatar.com/avatar/<?= md5(strtolower(trim(' '))); ?>?s=40&d=http://framework.zend.com/wiki/s/en/2148/48/_/images/icons/profilepics/anonymous.png" class="floatLeft" /><?= $remote; ?></a><br/>&nbsp;&nbsp;
                    <? /* if($details[$user][0]['user']->name): ?>
                        (<?=$details[$user][0]['user']->name;?>)
                    <? endif; */ ?>
                </h3>
                <ul>
                    <? foreach ($branches as $branch => $commits): ?>
                        <li class="nostyle ">
                            <strong><a href="https://github.com/<?= $remote; ?>/zf2/tree/<?= $branch; ?>" target="_blank"><?= $branch; ?></a></strong><br/>
                                <ul>
                                    <? foreach($commits as $i => $hash): ?>
                                        <li title="<?=htmlentities(nl2br($details['commits'][$hash]->getMessage()));?>" class="commit tooltip nostyle <? if(($i+1)%2): ?>even<? else: ?>odd<? endif; ?>"><a href="https://github.com/<?= $remote; ?>/zf2/commit/<?= $hash; ?>" target="_blank"><?= substr($hash, 0, 7); ?></a> <span class="date floatRight"><?= $details['commits'][$hash]->getCommitterTime()->format(false ?: 'M d, Y H:i O');?></span>
<br/><span style="padding: 5px 5px 0px 5px; display: block;"><?= htmlentities($details['commits'][$hash]->getSubject()); ?></span></li>
                                    <? endforeach; ?>                                 
                                </ul>
<? /*
    <?=$info['commit']->link;?> <span class="floatRight"><?=$info['commit']->committed_date->format(false ?: 'M d, Y H:i e');?></span></li>
 */?> 
                    <? endforeach; ?>
                </ul>
                </div>
            <? endforeach; ?>
        </div>
    <? endforeach; ?>
</div>
